start_booking:
  target:
    entity:
      integration: zwolle_parkeerloket
  fields:
    license_plate:
      required: true
      selector:
        text:

stop_booking:
  target:
    entity:
      integration: zwolle_parkeerloket
  fields:
    license_plate:
      required: true
      selector:
        text:

change_booking_time:
  target:
    entity:
      integration: zwolle_parkeerloket
  fields:
    license_plate:
      required: true
      selector:
        text:
    minutes:
      required: true
      selector:
        number:
          min: -1440
          max: 1440
          unit_of_measurement: min
          mode: box
